# Remote theme directory
#remote_theme: analytics-link/analytics-link.github.io
theme: jekyll-theme-minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
 # - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Jasmine Pankratz
description: "I'm Jasmine, an Industrial Engineer specialized in data science and analytics. I turn complex data into clear, actionable insights that help organizations make smarter decisions and run more efficiently. My work spans machine learning, statistical modeling, data visualization, and process improvement. I'm driven by curiosity and the satisfaction of solving real problems with data. Explore my projects below to see how I approach analysis and modeling."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Dallas, TX"
resume_url: /docs/Jasmine Pankratz Resume 2026.pdf
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/jasmine-pankratz" # Add your linkedln handle
github: "https://github.com/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

